### ISSUE TITLE
Enable redirects

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/support-how-to#103]

**Comment by codebyravi** [comment]
Fixed.

**Comment by robb-romans** [comment]
Reopening per meeting this afternoon.
Not done yet

To do, in order of priority:
- old-to-new article redirects
- retired article redirects to retired article landing page

Redirects in legacy platform: 
https://github.com/rackerlabs/nexus-control/blob/master/config/rewrites.d/support.rackspace.com.json
Redirects in Netlify:
https://github.com/rackerlabs/support-how-to/blob/master/static/_redirects

**Comment by robb-romans** [comment]
I learned a little `jq`. Thank you to various bloggers. 
To make this easier, flatten the first part of the json file from Nexus control (and fix the last line accordingly):
```
[
      {
          "description": "Force trailing slash",
```
then
To get only the retired articles redirects:
```cat support.rackspace.com.json | jq '.[] | select(.to=="/how-to/article-retired/") | .from' > retired-articles.txt```
This returns a flat list.
Then to get everything except the retired articles redirects:
```cat support.rackspace.com.json | jq '.[] | select(.to!="/how-to/article-retired/") | [.from,.to]' > redirects.txt```
This returns an array.
Files are attached.
[redirects.txt](https://github.com/rackerlabs/support-how-to/files/5133155/redirects.txt)
[retired-articles.txt](https://github.com/rackerlabs/support-how-to/files/5133156/retired-articles.txt)

**Comment by robb-romans** [comment]
Tested by team. Fixed.
