### ISSUE TITLE
How-to link in header 404

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/support-how-to#115]
![image](https://user-images.githubusercontent.com/730187/91056923-2db37680-e5ec-11ea-9f57-11c1f34b6d15.png)

Link points to https://docs.rackspace.com/support/how-to/
404
![image](https://user-images.githubusercontent.com/730187/91057024-50458f80-e5ec-11ea-9e15-0dea3d0d3fe4.png)

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 12 53 51 PM](https://user-images.githubusercontent.com/1606969/91221106-09ca6080-e6d2-11ea-8f1d-027585103426.png)

**Comment by robb-romans** [comment]
👍
