### ISSUE TITLE
Bug: FAQ expandable lists auto-expanding

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/support-how-to#116]
When you expand one of the FAQs, all the questions below that one also expand, though the + sign doesn't change:

<img width="940" alt="Screen Shot 2020-08-24 at 2 33 20 PM" src="https://user-images.githubusercontent.com/12717324/91087875-c65eec00-e616-11ea-9e17-208df0079204.png">

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 12 20 49 PM](https://user-images.githubusercontent.com/1606969/91218092-6d05c400-e6cd-11ea-8689-d50b48d92847.png)
![Screen Shot 2020-08-25 at 12 21 14 PM](https://user-images.githubusercontent.com/1606969/91218118-798a1c80-e6cd-11ea-8eae-7430b0b07ce7.png)
