### ISSUE TITLE
Safari mobile banner has outline on two of four sides

### ISSUE THREAD

**Issue by WilliamLoy** [rackerlabs/support-how-to#117]
![Image from iOS (13)](https://user-images.githubusercontent.com/18149544/91089080-a92b1d00-e618-11ea-85c7-4e15ac5c8885.jpg)

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 12 19 17 PM](https://user-images.githubusercontent.com/1606969/91217976-362fae00-e6cd-11ea-97ea-043330936935.png)
