### ISSUE TITLE
VMware Server Virtualization - broken link to "community forum"

### ISSUE THREAD

**Issue by kellgusta** [rackerlabs/support-how-to#120]
Very bottom of the Introduction page, there is a link to "Rackspace Managed Virtualization community forum" that connects to an invalid URL. If this page is in existence, the link should be fixed and then added to the FAQ and All Articles pages for VMware Server Virtualization as well.

**Comment by codebyravi** [comment]
https://community.rackspace.com/products/f/52
What is the correct link?

**Comment by robb-romans** [comment]
Community is DOA. Please just remove the link.

**Comment by WilliamLoy** [comment]
link has been removed
