### ISSUE TITLE
MS Edge: Navigation is not displayed properly for Rackspace Public Cloud 

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#121]
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/29145813/91090754-2ce60900-e61b-11ea-9dbe-84888b755f37.png">

The delineation between the different buttons is clear on legacy site.

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 12 10 52 PM](https://user-images.githubusercontent.com/1606969/91217240-07fd9e80-e6cc-11ea-83a9-4d7a9957b887.png)
