### ISSUE TITLE
VMware Server Virtualization - All Articles links to All Articles link

### ISSUE THREAD

**Issue by kellgusta** [rackerlabs/support-how-to#122]
All Articles has three links - the Introduction page, the FAQ and All Articles. Should be a list of all VMware Server Virtualization content - having the link to All Articles on the All Articles page is redundant

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 12 10 14 PM](https://user-images.githubusercontent.com/1606969/91217181-f1574780-e6cb-11ea-8a53-4ae33e48457b.png)
