### ISSUE TITLE
VMware Server Virtualization - How-To link is broken

### ISSUE THREAD

**Issue by kellgusta** [rackerlabs/support-how-to#123]
Selecting How-To from the navigation results in a Page Not Found, instead of bringing you you to the How-To landing page

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 12 51 43 PM](https://user-images.githubusercontent.com/1606969/91220897-bc4df380-e6d1-11ea-9b3b-cb6c93711c48.png)
