### ISSUE TITLE
MS Edge: Bold formatting is not applied to headers, links 

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#124]
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/29145813/91091588-6a976180-e61c-11ea-8583-d6be78da6561.png">

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 11 45 51 AM](https://user-images.githubusercontent.com/1606969/91214855-89533200-e6c8-11ea-8b14-61513e22b305.png)
