### ISSUE TITLE
Spacing issue on iPhone X 

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#125]
![image](https://user-images.githubusercontent.com/29145813/91097164-d382d780-e624-11ea-9f7d-d865fd6bb167.png)

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 11 44 41 AM](https://user-images.githubusercontent.com/1606969/91214735-5f9a0b00-e6c8-11ea-8462-f7b2a8861e39.png)
