### ISSUE TITLE
Need to migrate new content

### ISSUE THREAD

**Issue by catlook** [rackerlabs/support-how-to#129]
At some point, Ravi migrated all published content from the old How-To to the new How-To.  Since then, more articles have been published on only the old site. And some new content might have been published on only the new site.

Please identify and bring across the recently added content from the old site to the new one without losing any new content on the new site.

**Comment by WilliamLoy** [comment]
@catlook is this still in progress?

**Comment by catlook** [comment]
negative.  I'll close.
