### ISSUE TITLE
Lists are showing incorrectly in staging (at least)

### ISSUE THREAD

**Issue by catlook** [rackerlabs/support-how-to#130]
The articles in the new PR have numbered lists and numbers aren’t showing. For example, https://deploy-preview-102--docs-support-how-to.netlify.app/how-to/troubleshoot-onedrive-with-the-microsoft-support-and-recovery-assistant/ 

Bulleted lists don’t have bullets either.

PR: https://github.com/rackerlabs/support-how-to/pull/102

**Comment by catlook** [comment]
still showing incorrectly, even after forcing a rebuild.

**Comment by codebyravi** [comment]
This PR branch needs to updated with the master in order to show them.

**Comment by catlook** [comment]
the rebase fixed it, but boy it was tedious.  Thanks.
