### ISSUE TITLE
bullets fall outside paragraph margin

### ISSUE THREAD

**Issue by WilliamLoy** [rackerlabs/support-how-to#140]
![Screen Shot 2020-08-26 at 3 30 27 PM](https://user-images.githubusercontent.com/18149544/91353659-2be6e000-e7b1-11ea-802d-9589e6b6cf1a.png)

**Comment by codebyravi** [comment]
Fixed.

**Comment by codebyravi** [comment]
https://5f47cb6eeb76e10008f504d2--docs-support-how-to.netlify.app/support/how-to/rackspace-pdr-aws/
