### ISSUE TITLE
Header syntax not rendering

### ISSUE THREAD

**Issue by WilliamLoy** [rackerlabs/support-how-to#141]
![Screen Shot 2020-08-26 at 3 41 49 PM](https://user-images.githubusercontent.com/18149544/91354731-c5fb5800-e7b2-11ea-99ed-d9f38511fb09.png)

https://docs-support-how-to.netlify.app/support/how-to/logging-in-with-an-ssh-private-key-on-linuxmac/

**Comment by codebyravi** [comment]
Fixed.

**Comment by codebyravi** [comment]
https://5f47cb6eeb76e10008f504d2--docs-support-how-to.netlify.app/support/how-to/logging-in-with-an-ssh-private-key-on-linuxmac/
