### ISSUE TITLE
Callout boxes aren't formatting as callouts

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/support-how-to#142]
Note, Tip, Warning, and Important are all meant to format as colored boxes to highlight the text.

![Screen Shot 2020-08-26 at 3 48 28 PM](https://user-images.githubusercontent.com/12717324/91355277-8e40e000-e7b3-11ea-97d0-60d66aa78a1c.png)
![Screen Shot 2020-08-26 at 3 48 03 PM](https://user-images.githubusercontent.com/12717324/91355282-8f720d00-e7b3-11ea-8cfa-c0cd616f07ff.png)

**Comment by codebyravi** [comment]
Fixed.

**Comment by codebyravi** [comment]
https://5f47cb6eeb76e10008f504d2--docs-support-how-to.netlify.app/support/how-to/connecting-to-linux-from-mac-os-x-by-using-terminal/
