### ISSUE TITLE
Monospace text not rendering correctly

### ISSUE THREAD

**Issue by catlook** [rackerlabs/support-how-to#144]
Code between backticks (`) is supposed to render monospace which distinct formatting. It's not, and it's way too light.

example: https://github.com/rackerlabs/support-how-to/edit/master/content/how-to/cloud-servers/checking-linux-file-permissions-with-ls/index.md

example code: This article explains how to use the `ls` command to check Linux&reg; file permissions.
Being able to check the permissions on a file is useful, especially for
troubleshooting.

![image](https://user-images.githubusercontent.com/5709104/91355434-c0ead880-e7b3-11ea-8073-10b4276dcdaa.png)

**Comment by codebyravi** [comment]
Fixed.

**Comment by codebyravi** [comment]
https://5f47cb6eeb76e10008f504d2--docs-support-how-to.netlify.app/support/how-to/checking-linux-file-permissions-with-ls/

**Comment by catlook** [comment]
confirmed on the preview link you posted.
