### ISSUE TITLE
Author is incorrect

### ISSUE THREAD

**Issue by catlook** [rackerlabs/support-how-to#145]
The published article shows the last-modified user as the author instead of the author.  Pulling the wrong meta data element.

For example, https://docs-support-how-to.netlify.app/support/how-to/checking-linux-file-permissions-with-ls/

![image](https://user-images.githubusercontent.com/5709104/91355911-74ec6380-e7b4-11ea-9519-c362f4e949c4.png)

---
permalink: checking-linux-file-permissions-with-ls/
audit_date: '2016-06-22'
title: Check Linux file permissions with ls
type: article
created_date: '2011-11-23'
created_by: Jered Heeschen
last_modified_date: '2019-03-07'
last_modified_by: Cat Lookabaugh
product: Cloud Servers
product_url: cloud-servers
---

**Comment by codebyravi** [comment]
Is it supposed to take 'created_by'?

**Comment by catlook** [comment]
yes. created_by

**Comment by codebyravi** [comment]
https://5f47cb6eeb76e10008f504d2--docs-support-how-to.netlify.app/support/how-to/checking-linux-file-permissions-with-ls/

**Comment by catlook** [comment]
confirmed on your link
