### ISSUE TITLE
Bug: Sidebar product name

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/support-how-to#164]
The product name in the sidebar seems to be drawn from the `product_url` in the metadata instead of `product`:

<img width="337" alt="Screen Shot 2020-08-28 at 9 24 11 AM" src="https://user-images.githubusercontent.com/12717324/91578688-25bb4580-e910-11ea-86a4-95e6a691f6c5.png">

**Comment by stephamon** [comment]
For Alert Logic, the `product_url` is `rms-alert-logic` and `product` is `Alert Logic Security Solutions`

**Comment by codebyravi** [comment]
Fixed.

**Comment by WilliamLoy** [comment]
confirmed fixed
