### ISSUE TITLE
Bug: Table cell content isn't wrapping

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/support-how-to#165]
Content in a table cell isn't wrapping, so the tables stretch on for eternity:

<img width="1106" alt="Screen Shot 2020-08-28 at 9 25 17 AM" src="https://user-images.githubusercontent.com/12717324/91578785-4aafb880-e910-11ea-83db-529dc4bf5431.png">

**Comment by stephamon** [comment]
This is on https://docs-support-how-to.netlify.app/support/how-to/rms-alert-logic/

**Comment by codebyravi** [comment]
Fixed.

**Comment by WilliamLoy** [comment]
confirmed fixed
