### ISSUE TITLE
Bug: Managed Operations FAQ

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/support-how-to#170]
Broken link in the first FAQ to "Cloud Security Solutions" is supposed to go to https://docs.rackspace.com/support/support/how-to/are-cloud-servers-pci-dss-compliant/ but you get a 404 error

https://docs.rackspace.com/support//how-to/are-cloud-servers-pci-dss-compliant/ (the same article) is published but it's got an extra `/` after `support`

**Comment by codebyravi** [comment]
Fixed.
