### ISSUE TITLE
FAQ and All Articles links from sidebar are showing a 404

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#174]
https://docs.rackspace.com/support/how-to/reissue-or-revoke-and-replace-rackspace-ssl-certificates

https://docs.rackspace.com/support/how-to/vmware-os-mitigations-against-cpu-speculative-execution-vulnerabilities

https://docs.rackspace.com/support/how-to/ord1-data-center-consolidation-faq

https://docs.rackspace.com/support/how-to/rackspace-reseller-program

**Comment by Sterling463** [comment]
This seems to be affecting all articles

**Comment by codebyravi** [comment]
Fixed.

**Comment by Sterling463** [comment]
Still not working for me on MS Edge

**Comment by Sterling463** [comment]
https://docs.rackspace.com/support/how-to/getting-started-with-hosted-email/

This link is an example of the FAQ and all articles link not working

**Comment by WilliamLoy** [comment]
@Sterling463 can you check in Edge again please? Seems to work for me.

**Comment by Sterling463** [comment]
This one is still not working
