### ISSUE TITLE
Broken link on this page 

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#175]
https://docs.rackspace.com/support/how-to/id-federation-map-policies-permissions-cloud

Link is https://docs.rackspace.com/docs/rackspace-federation/attribmapping-basics/

And it is in the section of the page labelled 'Edit the mappings in your default Attribute Mapping Policy'

**Comment by Sterling463** [comment]
Link in section 'Set values with Attribute Mapping' is also broken

Below is link url 
https://docs.rackspace.com/docs/rackspace-federation/attribmap-reference/#attribmap-reference

**Comment by Sterling463** [comment]
Link in 'Assign Rackspace Permissions' is also broken. 

Link is https://docs.rackspace.com/docs/rackspace-federation/attribmapping-basics/full-roles/#full-roles-ug

**Comment by codebyravi** [comment]
'/docs' are not part of the support site.

**Comment by Sterling463** [comment]
The links are on the support site. They lead to the /docs site

**Comment by WilliamLoy** [comment]
attribmapping-basics doesn't exist. Replaced all mentions of it with https://docs.rackspace.com/docs/rackspace-federation/config-attribute-mapping/full-roles/
