### ISSUE TITLE
Missing image and faded images

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#188]
Article is here: https://docs.rackspace.com/support/how-to/encryption-fundamentals

![image](https://user-images.githubusercontent.com/29145813/91614661-90d43e80-e947-11ea-9176-cfb7afdbaf36.png)

These code blocks are barely visible
![image](https://user-images.githubusercontent.com/29145813/91614762-be20ec80-e947-11ea-9200-ab2df2c4502c.png)

**Comment by codebyravi** [comment]
Fixed.
