### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#190]
Article is here: https://docs.rackspace.com/support/how-to/encryption-fundamentals

These two links in the References section are broken

https://tim.dierks.org/2014/05/security-standards-and-name-changes-in.html

https://www.brynmawr.edu/math/people/stromquist/numbers/primitive.html

**Comment by codebyravi** [comment]
The URLs are not part of the Support Site.

**Comment by Sterling463** [comment]
![image](https://user-images.githubusercontent.com/29145813/91895700-49a6c000-ec5d-11ea-9911-65ca1cc174a8.png)
There is also some stray code in this section

**Comment by Sterling463** [comment]
Also curious if the source of the error is our site or theirs. If it theirs, then we can close this issue.

**Comment by WilliamLoy** [comment]
removed dead links and fixed code block
