### ISSUE TITLE
Several missing images 

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#203]
https://docs.rackspace.com/support/how-to/creating-dns-records-with-cloud-dns

![image](https://user-images.githubusercontent.com/29145813/91616287-042b7f80-e94b-11ea-8741-f0275d362b06.png)

![image](https://user-images.githubusercontent.com/29145813/91616324-12799b80-e94b-11ea-83ee-b5287e13cf37.png)

**Comment by codebyravi** [comment]
Fixed.
