### ISSUE TITLE
MS Edge Code blocks are not displaying properly 

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#209]
https://docs.rackspace.com/support/how-to/upgrade-a-cloud-databases-instance-from-mysql-56-to-mysql-57

![image](https://user-images.githubusercontent.com/29145813/91617194-1d353000-e94d-11ea-9146-bb43e9e0c6fd.png)

**Comment by codebyravi** [comment]
![Screen Shot 2020-09-01 at 8 54 17 AM](https://user-images.githubusercontent.com/1606969/91875710-b9eb1c80-ec30-11ea-846f-733abe21baab.png)

**Comment by codebyravi** [comment]
Fixed.

**Comment by Sterling463** [comment]
![image](https://user-images.githubusercontent.com/29145813/91894326-2713a780-ec5b-11ea-9416-8250a9e6eecf.png)
Looks like there is still some code that is outside of the code block tag?

**Comment by WilliamLoy** [comment]
Confirmed fixed.
