### ISSUE TITLE
Link gives a security error

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#212]
https://docs.rackspace.com/support/how-to/using-ssl-with-your-cloud-database-instance

Text to this link: https://ssl.rackspaceclouddb.com/ca-cert.pem

**Comment by codebyravi** [comment]
The browser thinks the URL is insecure. It is the problem with the external URL.

**Comment by Sterling463** [comment]
Understood. There are a bunch of links that have this behavior. I will close ticket
