### ISSUE TITLE
Issues found in testing test plan lines 186-192 (Robb)

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/support-how-to#213]
*Missing images on these pages:*

- https://docs.rackspace.com/support/how-to/block-or-restore-rackspace-email-access 
- https://docs.rackspace.com/support/how-to/import-email-address-data-into-outlook-2010-for-windows
- https://docs.rackspace.com/support/how-to/view-administrator-activity-in-the-cloud-office-control-panel
- https://docs.rackspace.com/support/how-to/import-email-address-data-into-outlook-2016-for-windows
- https://docs.rackspace.com/support/how-to/nested-imap-folders-in-apple-mail

*Broken links in these pages:*
- https://docs.rackspace.com/support/how-to/renaming-a-rackspace-email-address-overview
broken links to: 
Rename the email address
For instructions, see Rename a Rackspace Email address
broken link to:
Mobile clients
Iphone iOS
Android
Windows
All links in this paragraph broken:
Your devices are not receiving mail because they are configured to connect using the old email address. If you log in at apps.rackspace.com using the new email address, you can see that the mailbox is still receiving mail. Select your mail client in Desktop clients or Mobile clients for 

*Tables are poorly formatted on these pages:*
- https://docs.rackspace.com/support/how-to/cloud-office-support-terminology/

*** pausing testing at line 192 in test doc ***

**Comment by codebyravi** [comment]
There is neither content nor redirect for this URL: https://docs.rackspace.com/support/how-to/configure-a-renamed-email-address-configuration-for-windows-mobile-phone

**Comment by codebyravi** [comment]
Fixed.

**Comment by WilliamLoy** [comment]
All issues confirmed to be resolved.
