### ISSUE TITLE
Link click does not download a file

### ISSUE THREAD

**Issue by catlook** [rackerlabs/support-how-to#226]
https://docs.rackspace.com/support/how-to/quick-start-guide-create-your-first-website-on-cloud-servers 

when you click “sample HTML file” it should download a file

**Comment by codebyravi** [comment]
It is the security issue with the URL. It is not a part of the support site.

**Comment by catlook** [comment]
It works with the current production site!  I was able to download it just fine.

**Comment by codebyravi** [comment]
you need to accept the risk and download it. I cannot do anything with that.

**Comment by catlook** [comment]
ok closing this.  Ravi is sending me the syntax to serve this as a local file and I'll make a jira card to fix the article
