### ISSUE TITLE
Bug: malformed links

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/support-how-to#229]
https://docs.rackspace.com/support/how-to/update-billing-information-for-cloud-hosting/

Has several malformed links in the body of the article. This is not an issue in the currently published version.

<img width="929" alt="Screen Shot 2020-09-01 at 3 20 46 PM" src="https://user-images.githubusercontent.com/12717324/91901983-9e026d80-ec66-11ea-98c0-3e2fbc7b60c5.png">

**Comment by codebyravi** [comment]
Fixed.
