### ISSUE TITLE
Bug: Random text next to image

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/support-how-to#233]
https://docs.rackspace.com/support/how-to/removing-networks-from-a-cloud-server/ has the article title repeated in bold text to the right of the image in the article. This does not occur in the live version

<img width="852" alt="Screen Shot 2020-09-01 at 3 49 55 PM" src="https://user-images.githubusercontent.com/12717324/91904577-c4c2a300-ec6a-11ea-8d32-3425d9e94e71.png">

**Comment by stephamon** [comment]
seeing this behavior in https://docs.rackspace.com/support/how-to/create-an-isolated-cloud-network-and-attach-it-to-a-server as well

**Comment by stephamon** [comment]
Also https://docs.rackspace.com/support/how-to/configure-w3-total-cache-for-origin-pull-rackspace-cdn

<img width="911" alt="Screen Shot 2020-09-01 at 4 13 19 PM" src="https://user-images.githubusercontent.com/12717324/91906565-04d75500-ec6e-11ea-8fb6-72f3e67b7800.png">

**Comment by codebyravi** [comment]
Fixed.
