### ISSUE TITLE
broken link in migrate-your-email-by-using-the-self-service-migration-tool

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/support-how-to#234]
Broken link to https://docs.rackspace.com/support/how-to/adding-microsoft-exchange-mailboxes-0
Should be: https://docs.rackspace.com/support/how-to/adding-microsoft-exchange-mailboxes

**Comment by codebyravi** [comment]
Fixed.

**Comment by WilliamLoy** [comment]
confirmed fixed
