### ISSUE TITLE
All links under the header for the 'Popular technical articles and other resources' are showing 404

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#238]
Not sure if this is an issue with the markdown or the articles that they link to

https://docs.rackspace.com/support/how-to/cloud-databases-developer-resources-and-how-to-articles

**Comment by codebyravi** [comment]
The URLs are not part of the support site.

**Comment by WilliamLoy** [comment]
I removed the entire sections because the articles no longer exist.
