### ISSUE TITLE
broken link on how-to/recover-deleted-email-in-webmail

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/support-how-to#244]
On this page:
https://docs.rackspace.com/support/how-to/recover-deleted-email-in-webmail

"For more information on prerequisite terminology, see Cloud Office support terminology."
broken link to https://docs.rackspace.com/how-to/cloud-office-support-terminology

**Comment by codebyravi** [comment]
Fixed.

**Comment by WilliamLoy** [comment]
Confirmed fixed.
