### ISSUE TITLE
broken link on how-to/export-email-address-data-from-outlook-2010-for-windows

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/support-how-to#245]
On this page:
https://docs.rackspace.com/support/how-to/export-email-address-data-from-outlook-2010-for-windows

Link "see Import email address data into Outlook 2010 for Windows."
404 on https://docs.rackspace.com/support/how-to/import-email-address-data-into-outlook-2010

**Comment by codebyravi** [comment]
There is neither content nor redirect for the  https://docs.rackspace.com/support/how-to/import-email-address-data-into-outlook-2010.

**Comment by codebyravi** [comment]
I'm changing it to '/import-email-address-data-into-outlook-2010-for-windows/'

**Comment by WilliamLoy** [comment]
confirmed fixed
