### ISSUE TITLE
broken link on how-to/rename-a-rackspace-email-mailbox

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/support-how-to#248]
On this page:
https://docs.rackspace.com/support/how-to/rename-a-rackspace-email-mailbox

link "For a video tutorial of the following steps, see Rackspace Email - Adding/Editing/Renaming/Restoring."
404 on https://docs.rackspace.com/support/how-to/emailhelp.rackspace.com/l/add-edit-rename-rse-mailbox

**Comment by codebyravi** [comment]
Fixed.

**Comment by WilliamLoy** [comment]
confirmed fixed
