### ISSUE TITLE
broken links on how-to/email-spoofing-best-practices

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/support-how-to#250]
On this page:
https://docs.rackspace.com/support/how-to/email-spoofing-best-practices

Link to "If you would prefer a video tutorial see Rackspace Email - Spoofing: How to identify & protect your organization."
404 on https://emailhelp.rackspace.com/l/support/how-to-prevent-email-spoofing

Link to "Immediately change the password of your email account if you or your users provided that information at any point"
404 on https://docs.rackspace.com/support/how-to/change-rackspace-email-mailbox-password

Link to "Change a Rackspace email mailbox password"
404 on https://docs.rackspace.com/support/how-to/change-rackspace-email-mailbox-password

**Comment by codebyravi** [comment]
Fixed.

**Comment by WilliamLoy** [comment]
one link wasn't fixed but is now
