### ISSUE TITLE
Article gets a 404 error 

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#252]
https://docs.rackspace.com/support/how-to/configure-a-renamed-email-address-on-android-mobile-phone

**Comment by codebyravi** [comment]
this is the existing URL - https://docs.rackspace.com/support/how-to/configure-a-renamed-email-address-on-android-devices

**Comment by WilliamLoy** [comment]
This URL issue is resolved. The first link never existed.
