### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by catlook** [rackerlabs/support-how-to#274]
https://docs.rackspace.com/support/how-to/checking-for-a-security-compromise-rescue-mode-investigation

* In the article **Check for a security compromise: Back doors and intruders**, you learned some basic techniques for collecting the information needed to identify intruders who have compromised your server. 

* For more options and information on using chkrootkit, see **https://www.chkrootkit.org/README**.

* Summary

In **Checking for a security compromise: Backdoors and Intruders**, you learned some techniques to use to discover back doors and track intruders on your Cloud Server.

**Comment by codebyravi** [comment]
Fixed.

**Comment by catlook** [comment]
still broken...but Ravi is on the case!!

**Comment by catlook** [comment]
can you change the see https://www.chkrootkit.org/README to see http://www.chkrootkit.org/README ?  It isn't secured.

**Comment by catlook** [comment]
@codebyravi

**Comment by codebyravi** [comment]
Netlify is gonna throw a warning as a security vulnerability if we change it to http

**Comment by catlook** [comment]
How do we fix that error?

**Comment by catlook** [comment]
Is a warning ok?

**Comment by catlook** [comment]
https link doesn't work.  http does

**Comment by catlook** [comment]
the build in PR 390 has all green checkmarks.  Where is the warning? And will it publish with the warning?
