### ISSUE TITLE
https://docs.rackspace.com/support/how-to/troubleshoot-remote-desktop-services

### ISSUE THREAD

**Issue by WilliamLoy** [rackerlabs/support-how-to#278]
For help, see "How to change your server root admin password from your account". link is using https://docs.rackspace.com/support/how-to/support/how-to-change-your-server-rootadmin-password-from-your-account/ which produces a 404

**Comment by codebyravi** [comment]
Fixed.

**Comment by WilliamLoy** [comment]
confirmed fixed
