### ISSUE TITLE
Link to internal wiki page

### ISSUE THREAD

**Issue by catlook** [rackerlabs/support-how-to#283]
https://docs.rackspace.com/support/how-to/mysql-replication-masterslave

Contact your account manager and request setup of the SiteScope monitor. The URL should be the public IP of the monitoring server, for example https://68.23.45.32/check_replication.php

**https://wiki.rackspace.corp/Databases/MySQL/ReplicationMonitoringScript**

**Comment by Sterling463** [comment]
removing this wiki link since customers can't access it

**Comment by WilliamLoy** [comment]
@Sterling463 did that fix the issue
