### ISSUE TITLE
em dashes are not rendering on site

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#285]
<img width="762" alt="image" src="https://user-images.githubusercontent.com/29145813/92031751-bd64cd80-ed2e-11ea-94c3-501832c8d63b.png">

This is one example but it seems to be the case everywhere
https://docs.rackspace.com/support/how-to/early-adopters-set-an-archiving-retention-policy

**Comment by codebyravi** [comment]
Fixed.
