### ISSUE TITLE
Bug: Home page options xtra wide

### ISSUE THREAD

**Issue by chri2547** [rackerlabs/support-how-to#29]
<img width="1553" alt="Screen Shot 2020-08-13 at 1 10 04 PM" src="https://user-images.githubusercontent.com/35463610/90170951-60e14480-dd66-11ea-82fd-6fd05365f5d7.png">

**Comment by codebyravi** [comment]
fixed

**Comment by chri2547** [comment]
verified fix

**Comment by chri2547** [comment]
verified fix
