### ISSUE TITLE
Bug: to bullet or not to bullet

### ISSUE THREAD

**Issue by chri2547** [rackerlabs/support-how-to#32]
This page in the testing site: https://docs-support-how-to.netlify.app/how-to/rackspace-pdr/ does not have bullets in production https://support.rackspace.com/how-to/rackspace-pdr/

Link text is also smaller in the testing site.

<img width="34" alt="Screen Shot 2020-08-13 at 1 24 35 PM" src="https://user-images.githubusercontent.com/35463610/90172670-f978c400-dd68-11ea-8f1d-6d08b4528ec9.png">

**Comment by codebyravi** [comment]
fixed

**Comment by chri2547** [comment]
verified fix
