### ISSUE TITLE
Bug: Craziness with the getting started with hosted email page

### ISSUE THREAD

**Issue by chri2547** [rackerlabs/support-how-to#33]
https://docs-support-how-to.netlify.app/how-to/getting-started-with-hosted-email/

<img width="1590" alt="Screen Shot 2020-08-13 at 1 30 25 PM" src="https://user-images.githubusercontent.com/35463610/90172998-62603c00-dd69-11ea-83eb-b86c1706d5cb.png">

**Comment by codebyravi** [comment]
fixed

**Comment by chri2547** [comment]
verified fix
