### ISSUE TITLE
Bug: Broken image

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/support-how-to#332]
https://docs-support-how-to.netlify.app/support/how-to/rpc-openstack-faq

In the *General* section, under the fourth question "What are Rackspace Private Cloud's main differentiators?" there's a broken image. Looks like it's missing a closing `</img>` tag.

<img width="1011" alt="Screen Shot 2020-09-03 at 9 15 00 AM" src="https://user-images.githubusercontent.com/12717324/92126685-1a5f9280-edc6-11ea-8c6a-ef19f6f7c674.png">

<img width="722" alt="Screen Shot 2020-09-03 at 9 15 05 AM" src="https://user-images.githubusercontent.com/12717324/92126712-20557380-edc6-11ea-905a-93449f238413.png">

**Comment by codebyravi** [comment]
Fixed.
