### ISSUE TITLE
https://docs.rackspace.com/support/how-to/securing-the-cloud-addressing-cloud-computing-security-concerns-with-private-cloud

### ISSUE THREAD

**Issue by WilliamLoy** [rackerlabs/support-how-to#339]
Cloud computing in the public cloud has raised some security questions for businesses that have regulatory compliance requirements. 

public cloud link Is broken

**Comment by Sterling463** [comment]
Adding to PR

**Comment by Sterling463** [comment]
Please confirm fix and close
