### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by catlook** [rackerlabs/support-how-to#340]
https://docs.rackspace.com/support/how-to/design-and-build-cloud-servers-for-stability

Learn more about Cloud Block Storage best practices from this **blog post**.  (post is retired.  just remove this link)

**Cedexis** offers multiple solutions to improve performance and availability by load balancing between multiple cloud regions. 

Through an application-aware global content delivery network (CDN) platform, **Incapsula** provides any website and web application

**Soasta**

**Comment by codebyravi** [comment]
Fixed.

**Comment by catlook** [comment]
Cedaxis, Incapsula, and Soasta still all point to things with other names.  The text should match the destination.

**Comment by WilliamLoy** [comment]
The only thing I noticed that redirects is Soasta which appears to be intentional.
