### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by catlook** [rackerlabs/support-how-to#347]
https://docs.rackspace.com/support/how-to/the-hosting-spectrum-which-solution-fits-your-business

Choosing the right **hosting solution** is a very critical piece to your business.

 A **colocation strategy** requires that the customer select a vendor with a data center 

 **Managed Colocation** provides the desired level of control that businesses

 including the data center, network, devices, **virtualization** software, operating systems,

**Comment by Sterling463** [comment]
Fixed
