### ISSUE TITLE
Bug: No numbered lists

### ISSUE THREAD

**Issue by chri2547** [rackerlabs/support-how-to#35]
Should be numbered lists on https://docs-support-how-to.netlify.app/how-to/getting-started-with-hosted-email/#create-mailboxes

here is the example from prod: https://support.rackspace.com/how-to/getting-started-with-hosted-email/

**Comment by stephamon** [comment]
I'm seeing this error as well

**Comment by stephamon** [comment]
I'm still seeing issues with numbered lists

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 1 29 55 PM](https://user-images.githubusercontent.com/1606969/91224508-12716580-e6d7-11ea-832a-b4558ae850f7.png)

**Comment by chri2547** [comment]
verified fix.
