### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by catlook** [rackerlabs/support-how-to#359]
https://docs.rackspace.com/support/how-to/migrating-an-application-based-on-backbonejs-nodejs-and-mongodb-from-amazon-web-services

* You can find instructions for installing MongoDB on the Rackspace Cloud at the **MongoDB Documentation website**.  

(actually takes you to the doc page but says 404)

* Use **rsync** or SSH File Transfer Protocol (SFTP).

**Comment by Sterling463** [comment]
Fixed

**Comment by Sterling463** [comment]
checked in preview
