### ISSUE TITLE
Bug: No FAQ collapsable questions

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/support-how-to#40]
The questions on the FAQ page are meant to be expandable and they aren't rendering that way. I believe it's set to have h4 headers activate the styling.

production:
<img width="1074" alt="Screen Shot 2020-08-13 at 3 57 07 PM" src="https://user-images.githubusercontent.com/12717324/90186297-8d548b00-dd7d-11ea-8134-bb3dfe6f4d57.png">

testing:
<img width="1226" alt="Screen Shot 2020-08-13 at 3 57 13 PM" src="https://user-images.githubusercontent.com/12717324/90186309-934a6c00-dd7d-11ea-8bdb-6edf9f094486.png">

**Comment by codebyravi** [comment]
Fixed.
