### ISSUE TITLE
Broken link on add-an-access-list-rule-with-firewall-manager-v2 page

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/support-how-to#404]
On this page
https://docs.rackspace.com/support/how-to/add-an-access-list-rule-with-firewall-manager-v2/

Link to "delete an access link" not found. https://docs.rackspace.com/support/how-to/delete-an-access-list-with-firewall-manager-v2
Link target should be:
https://support.rackspace.com/how-to/delete-an-access-list-rule-with-firewall-manager-v2/

**Comment by WilliamLoy** [comment]
fixed this
