### ISSUE TITLE
Broken Link 

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#405]
https://docs.rackspace.com/support/how-to/managed-operations-faq

What does a Managed Operations Service Level account include?
Cloud Servers with a Managed Operations Service Level include access to a dedicated, 24x7x365 support team via phone, chat, and online support ticket. The team supports your servers from the OS up through the application stack of Microsoft SQL Server, .Net/IIS, and the LAMP stack on Linux. Your Cloud Server is regularly patched and updated. Monitoring services are included, with the Managed Operations team proactively responding to any alerts. We monitor up to two user-defined ports as well as user-defined URL content.

We provide free licensing for the Rackspace Cloud Backup file-based backup option ( standard Cloud Files storage fees apply).

**Comment by WilliamLoy** [comment]
fixed this
