### ISSUE TITLE
Broken link to Holland & Cloud Backup MySQL article

### ISSUE THREAD

**Issue by BadCrumpany** [rackerlabs/support-how-to#427]
Search finds the article, but clicking it navigates to a page not found
![Screen Shot 2020-09-11 at 5 52 06 PM](https://user-images.githubusercontent.com/6352040/93006679-f538f580-f524-11ea-81db-23ea6b976065.png)
![Screen Shot 2020-09-11 at 5 54 49 PM](https://user-images.githubusercontent.com/6352040/93006680-f8cc7c80-f524-11ea-96e6-30f679994be0.png)

**Comment by WilliamLoy** [comment]
fixed this
