### ISSUE TITLE
Bug: Sidebar text displays article title rather than product name

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/support-how-to#43]
The sidebar is meant to show the product name and then the three links (Introduction, FAQ, All articles) however it is currently displaying the name of the article instead:

<img width="1201" alt="Screen Shot 2020-08-13 at 4 03 08 PM" src="https://user-images.githubusercontent.com/12717324/90186862-7ebaa380-dd7e-11ea-9e76-6b3acb0293cc.png">

**Comment by codebyravi** [comment]
fixed
