### ISSUE TITLE
Install and use Let's Encrypt link broken

### ISSUE THREAD

**Issue by BadCrumpany** [rackerlabs/support-how-to#432]
Link
https://docs.rackspace.com/support/how-to/install-and-use-the-lets-encrypt-certbot-utility-on-centos7-with-apache/?_ga=2.39229859.1876286706.1600047080-112332087.1598996059

![Screen Shot 2020-09-15 at 12 23 06 PM](https://user-images.githubusercontent.com/6352040/93243765-4a0b8480-f74e-11ea-91d5-ced0d31935a6.png)
![Screen Shot 2020-09-15 at 12 23 14 PM](https://user-images.githubusercontent.com/6352040/93243773-4bd54800-f74e-11ea-879d-ec248864aa66.png)

Sends to page not found

**Comment by WilliamLoy** [comment]
this has been fixed
