### ISSUE TITLE
Migrate to a new physical host link broken

### ISSUE THREAD

**Issue by BadCrumpany** [rackerlabs/support-how-to#433]
Link: https://docs.rackspace.com/support/how-to/migrate-a-cloud-server-to-a-new-physical-host/?_ga=2.203749648.1876286706.1600047080-112332087.1598996059
![Screen Shot 2020-09-15 at 12 26 27 PM](https://user-images.githubusercontent.com/6352040/93244070-c3a37280-f74e-11ea-9df6-97b09403887d.png)
![Screen Shot 2020-09-15 at 12 26 33 PM](https://user-images.githubusercontent.com/6352040/93244081-c56d3600-f74e-11ea-8398-89f6e1cd48c3.png)

Sends to page not found

**Comment by WilliamLoy** [comment]
this now works
