### ISSUE TITLE
Broken link for Upgrade Citrix Xen Server Tools for Windows Cloud Servers

### ISSUE THREAD

**Issue by BadCrumpany** [rackerlabs/support-how-to#436]
Goes to Page Not Found:
![Screen Shot 2020-09-16 at 2 28 13 PM](https://user-images.githubusercontent.com/6352040/93383270-fe79d900-f828-11ea-8d1d-d79d892bf9e6.png)
![Screen Shot 2020-09-16 at 2 28 18 PM](https://user-images.githubusercontent.com/6352040/93383273-ffab0600-f828-11ea-9a80-d53ad3c13d63.png)

Link
https://docs.rackspace.com/support/how-to/upgrade-citrix-xen-server-tools-for-windows-cloud-servers/?_ga=2.38048419.1876286706.1600047080-112332087.1598996059

**Comment by WilliamLoy** [comment]
@BadCrumpany https://docs.rackspace.com/support/how-to/upgrade-citrix-xenserver-tools-for-windows-cloud-servers/  Is the correct link I believe. Can you confirm?

**Comment by WilliamLoy** [comment]
Fixed this
