### ISSUE TITLE
Bug: Button size not consistent

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/support-how-to#44]
The buttons seem to have changed to be sized based on the length of the text inside rather than a static width:

production:
<img width="261" alt="Screen Shot 2020-08-13 at 4 04 58 PM" src="https://user-images.githubusercontent.com/12717324/90186971-a7db3400-dd7e-11ea-819a-d5e93130a599.png">

test:
<img width="294" alt="Screen Shot 2020-08-13 at 4 05 03 PM" src="https://user-images.githubusercontent.com/12717324/90186978-ab6ebb00-dd7e-11ea-8447-a78a6a6bd488.png">

**Comment by codebyravi** [comment]
fixed
