### ISSUE TITLE
Search results count is not accurate

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#526]
Example= searching for networking fundamentals shows that there are 12 results but only 11 results are displayed

**Comment by Sterling463** [comment]
This is not a consistent issue

**Comment by Sterling463** [comment]
searching for networking fundamentals now shows 7 instances of the same article

**Comment by codebyravi** [comment]
Fixed.

**Comment by robb-romans** [comment]
Verified fixed
