### ISSUE TITLE
Section title in drop down instead of available on page

### ISSUE THREAD

**Issue by BadCrumpany** [rackerlabs/support-how-to#56]
Should be:
https://support.rackspace.com/how-to/dedicated-hosting-faq/
![Screen Shot 2020-08-18 at 1 14 44 PM](https://user-images.githubusercontent.com/6352040/90549931-d5482900-e154-11ea-86ea-27ff2bddeb38.png)

Showing https://docs-support-how-to.netlify.app/how-to/dedicated-hosting-faq/
![Screen Shot 2020-08-18 at 1 15 49 PM](https://user-images.githubusercontent.com/6352040/90550029-fa3c9c00-e154-11ea-9faf-f04b81e67e17.png)

After opening expand:
![Screen Shot 2020-08-18 at 1 15 58 PM](https://user-images.githubusercontent.com/6352040/90550072-0a547b80-e155-11ea-8096-0bcf20c0540c.png)

**Comment by BadCrumpany** [comment]
https://docs-support-how-to.netlify.app/how-to/network-device-reboot-faq/
![Screen Shot 2020-08-18 at 1 33 19 PM](https://user-images.githubusercontent.com/6352040/90551782-77691080-e157-11ea-8b71-14c92bfd1f5e.png)
![Screen Shot 2020-08-18 at 1 33 29 PM](https://user-images.githubusercontent.com/6352040/90551789-7a640100-e157-11ea-8e16-01b78b1423fe.png)

How it should appear:
https://support.rackspace.com/how-to/network-device-reboot-faq/
![Screen Shot 2020-08-18 at 1 34 19 PM](https://user-images.githubusercontent.com/6352040/90551840-8e0f6780-e157-11ea-83dd-2906d8900951.png)

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 1 23 32 PM](https://user-images.githubusercontent.com/1606969/91223902-2ec0d280-e6d6-11ea-9518-1df045bcb745.png)

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 1 24 03 PM](https://user-images.githubusercontent.com/1606969/91223972-4009df00-e6d6-11ea-8604-2320c7a665b4.png)

**Comment by Sterling463** [comment]
Fixed
