### ISSUE TITLE
support.rackspace.com main title spacing mobile safari

### ISSUE THREAD

**Issue by WilliamLoy** [rackerlabs/support-how-to#59]
There is no spacing between the words Rackspace Support and Documentation.

**Comment by WilliamLoy** [comment]
![Image from iOS (14)](https://user-images.githubusercontent.com/18149544/91089277-fa3b1100-e618-11ea-9ba1-db9307a68f9f.jpg)

**Comment by WilliamLoy** [comment]
@codebyravi

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 1 22 19 PM](https://user-images.githubusercontent.com/1606969/91223789-033de800-e6d6-11ea-8ba5-d3abeabfac56.png)
