### ISSUE TITLE
Some links in search results are broken- I am including one example below

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/support-how-to#594]
Link was trying to take me here: 

https://docs.rackspace.com/support/how-to/delete-users-from-customer-portal/

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/29145813/96478370-3942a880-11fd-11eb-8070-06672341b728.png">

**Comment by Sterling463** [comment]
Another example 

https://docs.rackspace.com/support/how-to/delete-users-from-customer-portal/

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/29145813/96478766-b1a96980-11fd-11eb-9999-1583921ac89a.png">

**Comment by codebyravi** [comment]
Fixed.
