### ISSUE TITLE
[Firefox] Broken Image Links

### ISSUE THREAD

**Issue by BadCrumpany** [rackerlabs/support-how-to#61]
https://docs-support-how-to.netlify.app/how-to/create-an-object-group-with-firewall-manager-v2/

![Screen Shot 2020-08-18 at 1 20 47 PM](https://user-images.githubusercontent.com/6352040/90550560-bac27f80-e155-11ea-94e2-f0c89e11e4c5.png)

**Comment by BadCrumpany** [comment]
https://docs-support-how-to.netlify.app/how-to/add-an-access-list-rule-with-firewall-manager-v2/
![Screen Shot 2020-08-18 at 1 23 45 PM](https://user-images.githubusercontent.com/6352040/90550817-11c85480-e156-11ea-9aae-9a521ee9cd4f.png)

**Comment by BadCrumpany** [comment]
https://docs-support-how-to.netlify.app/how-to/delete-an-access-list-rule-with-firewall-manager-v2/
![Screen Shot 2020-08-18 at 1 26 46 PM](https://user-images.githubusercontent.com/6352040/90551122-7e435380-e156-11ea-8b2c-924b09c05814.png)

**Comment by BadCrumpany** [comment]
https://docs-support-how-to.netlify.app/how-to/delete-an-object-group-with-firewall-manager-v2/
![Screen Shot 2020-08-18 at 1 27 36 PM](https://user-images.githubusercontent.com/6352040/90551193-99ae5e80-e156-11ea-8fec-51e36cbf5f30.png)

**Comment by BadCrumpany** [comment]
https://docs-support-how-to.netlify.app/how-to/modify-an-access-lists-execution-order-with-firewall-manager-v2/
![Screen Shot 2020-08-18 at 1 30 38 PM](https://user-images.githubusercontent.com/6352040/90551495-088bb780-e157-11ea-8360-9db30ff0922a.png)

**Comment by BadCrumpany** [comment]
https://docs-support-how-to.netlify.app/how-to/modify-an-object-group-with-firewall-manager-v2/
![Screen Shot 2020-08-18 at 1 31 15 PM](https://user-images.githubusercontent.com/6352040/90551549-1ccfb480-e157-11ea-838c-00052dc83736.png)

**Comment by BadCrumpany** [comment]
https://docs-support-how-to.netlify.app/how-to/view-an-access-list-rules-with-firewall-manager-v2/
![Screen Shot 2020-08-18 at 1 37 15 PM](https://user-images.githubusercontent.com/6352040/90552186-0e35cd00-e158-11ea-844d-b50e879d9dab.png)

**Comment by BadCrumpany** [comment]
https://docs-support-how-to.netlify.app/how-to/view-an-object-group-with-firewall-manager-v2/
![Screen Shot 2020-08-18 at 1 39 05 PM](https://user-images.githubusercontent.com/6352040/90552291-33c2d680-e158-11ea-9c5f-6c6df4419874.png)

**Comment by Sterling463** [comment]
Confirmed fixed
