### ISSUE TITLE
Bug: RPC-V all articles page does not have any content

### ISSUE THREAD

**Issue by chri2547** [rackerlabs/support-how-to#65]
From production: https://support.rackspace.com/how-to/rpc-vmware-all-articles/

In new site: https://docs-support-how-to.netlify.app/how-to/rpc-vmware-all-articles/

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 1 02 48 PM](https://user-images.githubusercontent.com/1606969/91221905-48144f80-e6d3-11ea-9f29-f88160ece504.png)

**Comment by chri2547** [comment]
fix verified.
