### ISSUE TITLE
[Firefox] Indent section text

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/support-how-to#71]
![image](https://user-images.githubusercontent.com/730187/90552434-71276400-e158-11ea-8f06-d75ba10125e2.png)

**Comment by codebyravi** [comment]
Fixed.

**Comment by codebyravi** [comment]
Fixed.

**Comment by robb-romans** [comment]
these still need indented
https://docs-support-how-to.netlify.app/support/how-to/dedicated-hosting-faq
![image](https://user-images.githubusercontent.com/730187/91064923-7e7b9d00-e5f5-11ea-8963-69f223cd096c.png)

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 1 01 43 PM](https://user-images.githubusercontent.com/1606969/91221840-22874600-e6d3-11ea-842a-fb36737c03fc.png)

**Comment by robb-romans** [comment]
👍
