### ISSUE TITLE
numbers and bullets do not display safari mobile

### ISSUE THREAD

**Issue by WilliamLoy** [rackerlabs/support-how-to#72]
Numbers and bullets are not displayed in articles.

**Comment by stephamon** [comment]
@codebyravi I'm seeing this issue still on Chrome desktop

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 12 59 53 PM](https://user-images.githubusercontent.com/1606969/91221697-e05e0480-e6d2-11ea-862d-80149f276a54.png)
