### ISSUE TITLE
[Firefox] Some aspects of page layout did not transition over

### ISSUE THREAD

**Issue by BadCrumpany** [rackerlabs/support-how-to#75]
Don't know if this is intentional but for instance, the grey background on certain sections here:
https://support.rackspace.com/how-to/#cloud-office
![Screen Shot 2020-08-18 at 1 44 37 PM](https://user-images.githubusercontent.com/6352040/90552843-0cb8d480-e159-11ea-9a2f-d857fcb3af95.png)

are not present on the new version:
https://docs-support-how-to.netlify.app/how-to/#cloud-office
![Screen Shot 2020-08-18 at 1 45 51 PM](https://user-images.githubusercontent.com/6352040/90552899-25c18580-e159-11ea-90fb-6471e3fa037c.png)

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 12 59 21 PM](https://user-images.githubusercontent.com/1606969/91221646-cde3cb00-e6d2-11ea-9091-d4a411a288fb.png)

**Comment by Sterling463** [comment]
confirmed fixed.
