### ISSUE TITLE
[Firefox] Missing images in delete-an-object-group-with-firewall-manager-v2/

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/support-how-to#78]
https://docs-support-how-to.netlify.app/how-to/delete-an-object-group-with-firewall-manager-v2/

![image](https://user-images.githubusercontent.com/730187/90553384-e9daf000-e159-11ea-8963-343fe5775d7c.png)

**Comment by robb-romans** [comment]
Also https://docs-support-how-to.netlify.app/how-to/delete-an-access-list-rule-with-firewall-manager-v2/

**Comment by robb-romans** [comment]
Also https://docs-support-how-to.netlify.app/how-to/create-an-object-group-with-firewall-manager-v2/

**Comment by robb-romans** [comment]
Also https://docs-support-how-to.netlify.app/how-to/add-an-access-list-rule-with-firewall-manager-v2/

**Comment by robb-romans** [comment]
@codebyravi This one still broken:
https://docs-support-how-to.netlify.app/how-to/delete-an-access-list-rule-with-firewall-manager-v2/

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 12 58 44 PM](https://user-images.githubusercontent.com/1606969/91221599-b73d7400-e6d2-11ea-941f-ad5209fb8325.png)

**Comment by robb-romans** [comment]
👍
