### ISSUE TITLE
[Firefox] Disclaimer/Footer is bigger than original

### ISSUE THREAD

**Issue by BadCrumpany** [rackerlabs/support-how-to#79]
Original: https://support.rackspace.com/how-to/account-management/
![Screen Shot 2020-08-18 at 1 51 00 PM](https://user-images.githubusercontent.com/6352040/90553455-070fbe80-e15a-11ea-82b0-81a1f5c2f46f.png)

New: https://docs-support-how-to.netlify.app/how-to/account-management/
![Screen Shot 2020-08-18 at 1 50 54 PM](https://user-images.githubusercontent.com/6352040/90553487-1262ea00-e15a-11ea-97f5-985b9b9b89b6.png)

**Comment by Sterling463** [comment]
still visible

**Comment by WilliamLoy** [comment]
fixed
