### ISSUE TITLE
Side navigation bar can be narrower

### ISSUE THREAD

**Issue by catlook** [rackerlabs/support-how-to#80]
To give more real estate to the articles.  Also middle table column is messed up in this case:

![image](https://user-images.githubusercontent.com/5709104/90553485-1131bd00-e15a-11ea-926f-7a2ecfb6c5b9.png)

**Comment by catlook** [comment]
does not look fixed to me.

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 12 56 06 PM](https://user-images.githubusercontent.com/1606969/91221322-59109100-e6d2-11ea-8e3a-a236fa69b1d1.png)

**Comment by catlook** [comment]
confirmed
