### ISSUE TITLE
[Firefox] "Experience what Rackspace has to offer" not centered

### ISSUE THREAD

**Issue by BadCrumpany** [rackerlabs/support-how-to#81]
Original: https://support.rackspace.com/how-to/account-management/
![Screen Shot 2020-08-18 at 1 55 22 PM](https://user-images.githubusercontent.com/6352040/90553724-7a193500-e15a-11ea-9ad6-6a2906230200.png)

New: https://docs-support-how-to.netlify.app/how-to/account-management/
![Screen Shot 2020-08-18 at 1 54 13 PM](https://user-images.githubusercontent.com/6352040/90553784-8e5d3200-e15a-11ea-8ecd-836e39aaebfb.png)

**Comment by codebyravi** [comment]
![Screen Shot 2020-08-25 at 12 31 13 PM](https://user-images.githubusercontent.com/1606969/91219050-dfc36f00-e6ce-11ea-9a06-c4b9b4760e75.png)

**Comment by Sterling463** [comment]
Confirmed fixed
