### ISSUE TITLE
[Firefox] broken link to https://www.rackspace.com/openstack/private/resources

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/support-how-to#82]
![image](https://user-images.githubusercontent.com/730187/90554014-e6943400-e15a-11ea-8a9b-c8b0cb5fce2c.png)

From
https://docs-support-how-to.netlify.app/how-to/rpc-openstack/
![image](https://user-images.githubusercontent.com/730187/90554074-f90e6d80-e15a-11ea-9043-8670225cab97.png)

**Comment by codebyravi** [comment]
This is from the rackspace.com site. It is not part of support-how-to

**Comment by robb-romans** [comment]
the how-to (tries to) link to this site

**Comment by codebyravi** [comment]
I need more light on this issue.

**Comment by robb-romans** [comment]
On this page https://docs-support-how-to.netlify.app/support/how-to/rpc-openstack/
![image](https://user-images.githubusercontent.com/730187/91220115-4d789680-e6e1-11ea-9f2c-84566cba77dc.png)

**Comment by robb-romans** [comment]
Change the link from
https://www.rackspace.com/openstack/private/resources
to
https://www.rackspace.com/cloud/private

**Comment by robb-romans** [comment]
![image](https://user-images.githubusercontent.com/730187/91356754-c6492280-e7b5-11ea-9423-5cdbc178751f.png)
